### ISSUE TITLE
no makefile

### ISSUE THREAD

**Issue by zephyr-de-lest** [littlstar/soil#2]

**Comment by drs-m** [comment]
!

**Comment by jwerle** [comment]
In `0.1.0, try running:

```sh
./configure
make
```

**Comment by bily-101** [comment]
It won't let me make it if I dont have clib installed.

**Comment by jwerle** [comment]
fixed!

**Comment by bily-101** [comment]
Great! I ended up installing clib to install it anyway, thanks for the fast response!

**Comment by jwerle** [comment]
No problem! Good luck!
